Remove results tab when results not published yet
Sapphire-CM/Sapphire pull request #613
Opened 2023-04-20 14:12 UTC by amelsmajic

This fixes the issue #608.

I'm not sure if this is the correct way to do this. Any input @matthee?

2023-07-11 23:09 UTC, matthee requested changes
Hi Amel,

thanks for your contribution!

There are three things I would like you to change: First of all, I think there is a sneaky bug, please refer to the inline code comment and make sure to fix it. Second, please extract this functionality into a method. And last but not least, please add tests, you might have catched that bug mentioned above on your own 😉

2023-07-11 23:09 UTC, matthee commented on app/views/exercises/_subnav.html.erb
> +  <%= subnav_item(:megaphone, "Results", term_result_path(exercise.term, exercise), params[:controller] == "student_results") if policy(StudentResultsPolicy.term_policy_record(exercise.term)).index?
Have you tested this? I believe there will be an error raised when the student hasn't created a submission for this exercise. You might want to do this check differently. For example:

```ruby
Submission.active.for_account(current_account).for_exercise(exercise).first.try(:result_published?)
```

I would also like to see this functionality wrapped in a method, like `exercise.results_published_for_account?(current_account)`, but I'm open to your suggestions and API.

2023-08-16 15:53 UTC, amelsmajic commented
I have now added tests and a wrapper in Exercise with the suggested code instead of my own.

The branch is already re-based on master and is ready to be merged.

2024-01-21 10:13 UTC, matthee commented
Great! Thank you for your contribution!

2024-01-21 10:13 UTC, merged